services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  flightmngr:
    image: ghcr.io/scalabilityissues/flight-manager:main
    pull_policy: always
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:pwd@flightmngr-db:5432
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: "rabbitmq"
    ports:
      - 60051:50051

  flightmngr-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - flightmngr-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd

  ticketsvc:
    image: ghcr.io/scalabilityissues/ticket-service:master
    pull_policy: always
    restart: unless-stopped
    environment:
      DATABASE_URL: "mongodb://mongo:mongo@ticketsvc-db:27017/"
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
    ports:
      - 60053:50051

  ticketsvc-db:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - ticketsvc-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  validationsvc:
    image: ghcr.io/scalabilityissues/validation-service:master
    pull_policy: always
    restart: unless-stopped
    environment:
      - GENERATE_SIGNING_KEY=true
    ports:
      - 60054:50051

  server:
    build: .
    restart: unless-stopped
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SMTP_PORT: "1025"

  mailsvc:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  flightmngr-pgdata:
  ticketsvc-mongo:
